// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first (like Next.js does), then fall back to .env
dotenv.config({ path: ".env.local" });
dotenv.config(); // This will load .env but won't override .env.local values

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL! ,
  },
});
